<a href="https://colab.research.google.com/github/Priangshu-18/Numpy-Basics/blob/main/NumPy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!cat /proc/cpuinfo

processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 79
model name	: Intel(R) Xeon(R) CPU @ 2.20GHz
stepping	: 0
microcode	: 0xffffffff
cpu MHz		: 2199.998
cache size	: 56320 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat md_clear arch_capabilities
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa mmio_stale_data retbleed bhi
bogomips	: 4399.99
clflush size	: 64
cache_alignment	: 64
ad

In [ ]:
!cat /proc/meminfo

MemTotal:       13289424 kB
MemFree:         7960060 kB
MemAvailable:   12261352 kB
Buffers:          386904 kB
Cached:          4087548 kB
SwapCached:            0 kB
Active:           711164 kB
Inactive:        4325236 kB
Active(anon):       1288 kB
Inactive(anon):   562468 kB
Active(file):     709876 kB
Inactive(file):  3762768 kB
Unevictable:           8 kB
Mlocked:               8 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:              1784 kB
Writeback:             0 kB
AnonPages:        561720 kB
Mapped:           322696 kB
Shmem:              1800 kB
KReclaimable:     139176 kB
Slab:             178952 kB
SReclaimable:     139176 kB
SUnreclaim:        39776 kB
KernelStack:        5372 kB
PageTables:         9368 kB
SecPageTables:         0 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     6644712 kB
Committed_AS:    2568552 kB
VmallocTotal:   34359738367 kB
VmallocUsed:       12024 kB
VmallocChunk:    

# NumPy- Numerical Python

List vs Numpy Time Comparison

In [ ]:
import numpy as np

In [ ]:
from time import process_time

In [ ]:
my_list = [i for i in range(100)]

start_time = process_time()

my_list = [i+5 for i in my_list]

end_time = process_time()

print(end_time - start_time)

0.00010759799999959796


In [ ]:
numpy_array = np.array([i for i in range(100)])

start_time = process_time()

numpy_array += 5

end_time = process_time()

print(end_time - start_time)

0.00011738299999919377


For smaller values list is better but for more number of values numpy is time saving

In [ ]:
my_list = [i for i in range(10000)]

start_time = process_time()

my_list = [i+5 for i in my_list]

end_time = process_time()

print(end_time - start_time)

0.0008272919999985362


In [ ]:
numpy_array = np.array([i for i in range(10000)])

start_time = process_time()

numpy_array += 5

end_time = process_time()

print(end_time - start_time)

0.00015277099999977395


# NumPy Arrays

In [ ]:
import numpy as np

1D NumPy Array

In [ ]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
np_array.shape

(5,)

2D NumPy Array

In [ ]:
TwoD_Numpy_array = np.array([(1,2,3),(4,5,6)])
print(TwoD_Numpy_array)

[[1 2 3]
 [4 5 6]]


In [ ]:
TwoD_Numpy_array.shape

(2, 3)

Initial Placeholders in NumPy array

In [ ]:
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
z = np.full((3,4), 8)
print(z)

[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]


In [ ]:
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Random Values in NumPy Array

In [ ]:
import numpy as np
a = np.random.random((3,4))
print(a)

[[0.29564183 0.50951631 0.04986925 0.72775737]
 [0.92599009 0.37918315 0.62473741 0.84244705]
 [0.24866501 0.51885374 0.66147406 0.56582493]]


In [ ]:
import numpy as np
a = np.random.randint(10,100,(3,4))
print(a)

[[16 49 46 86]
 [35 30 55 95]
 [59 15 30 51]]


In [ ]:
# Array with evenly spaced values
a = np.linspace(10,30,6)
print(a)

# Array with evenly spaced values with steps specification
a = np.arange(10,30,5)
print(a)

[10. 14. 18. 22. 26. 30.]
[10 15 20 25]


In [ ]:
# List to numpy array
list_1 = [1,2,3,4,5]
numpy_array = np.asarray(list_1)
print(numpy_array)
type(numpy_array)

[1 2 3 4 5]


numpy.ndarray

Analyzing array

In [ ]:
a = np.random.randint(10,100,(5,5))

In [ ]:
print(a)

[[55 38 38 28 38]
 [15 12 13 15 83]
 [30 51 40 11 15]
 [43 82 86 66 59]
 [88 73 94 94 62]]


In [ ]:
print(a.shape) # 5 x 5 matrix

print(a.ndim) # Dimentional array

print(a.dtype) # datatype

print(a.size) # Total number of elements in the array

(5, 5)
2
int64
25


Array Operations

In [ ]:
a = np.random.randint(1,10,(5,5))
b = np.random.randint(10,20,(5,5))
print(a)
print(b)

[[9 6 4 2 9]
 [6 2 7 8 3]
 [7 3 9 4 5]
 [1 7 1 5 6]
 [3 6 8 6 4]]
[[10 18 15 10 13]
 [14 17 10 12 13]
 [19 13 18 11 18]
 [15 10 15 12 12]
 [19 16 18 15 15]]


In [ ]:
print(a+b)
print(b-a)
print(a*b)
print(a/b)

# or

print(np.add(a,b))
print(np.subtract(b,a))

[[19 24 19 12 22]
 [20 19 17 20 16]
 [26 16 27 15 23]
 [16 17 16 17 18]
 [22 22 26 21 19]]
[[ 1 12 11  8  4]
 [ 8 15  3  4 10]
 [12 10  9  7 13]
 [14  3 14  7  6]
 [16 10 10  9 11]]
[[ 90 108  60  20 117]
 [ 84  34  70  96  39]
 [133  39 162  44  90]
 [ 15  70  15  60  72]
 [ 57  96 144  90  60]]
[[0.9        0.33333333 0.26666667 0.2        0.69230769]
 [0.42857143 0.11764706 0.7        0.66666667 0.23076923]
 [0.36842105 0.23076923 0.5        0.36363636 0.27777778]
 [0.06666667 0.7        0.06666667 0.41666667 0.5       ]
 [0.15789474 0.375      0.44444444 0.4        0.26666667]]
[[19 24 19 12 22]
 [20 19 17 20 16]
 [26 16 27 15 23]
 [16 17 16 17 18]
 [22 22 26 21 19]]
[[ 1 12 11  8  4]
 [ 8 15  3  4 10]
 [12 10  9  7 13]
 [14  3 14  7  6]
 [16 10 10  9 11]]


In [ ]:
trans = np.transpose(a)
print(trans)

# or

trans_2 = a.T
print(trans_2)

[[9 6 7 1 3]
 [6 2 3 7 6]
 [4 7 9 1 8]
 [2 8 4 5 6]
 [9 3 5 6 4]]
[[9 6 7 1 3]
 [6 2 3 7 6]
 [4 7 9 1 8]
 [2 8 4 5 6]
 [9 3 5 6 4]]


In [ ]:
a = np.random.randint(1,10,(2,3))
print(a)
print(a.shape)

[[8 7 7]
 [9 5 7]]
(2, 3)


In [ ]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[8 7]
 [7 9]
 [5 7]]
(3, 2)
